# streamlit + MYSQL 서비스 구현 영역
version: "3.9"

services:
  mydb:
    image: mysql:8.0
    container_name: mydb
    environment:
      MYSQL_ROOT_PASSWORD: rootpw
      MYSQL_DATABASE: testdb
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpw
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  
  streamlit:
    build: ./app_ex
    container_name: streamlit-1
    ports:
      - "8501:8501"
    volumes:
      - ./app_ex:/app
    environment:
      - MYSQL_HOST=mydb
      - MYSQL_PORT=3306 # 컨테이너 내 포트를 의미
      - MYSQL_USER=testuser
      - MYSQL_PASSWORD=testpw
      - MYSQL_DATABASE=testdb
    depends_on:
      - mydb

volumes:
  mysql_data: