version: "3.8"
services:
  streamlit:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    depends_on:
      - mlflow

  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.11.1
    command: mlflow ui --host 0.0.0.0 --port 5000
    ports:
      - "5050:5000"
    volumes:
      - ./mlruns:/mlflow/mlruns